
defaults:
  - override hydra/launcher: submitit_local

exp_name: BMPC
debug: false
device: cuda

# environment
task: humanoid
obs: state

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 10000

# BMPC settings
## value learning
use_v_instead_q: true
nstep_td_horizon: 1 # work only when use_v_instead_q=true
min_td_target: false # work only when use_v_instead_q=false
## loss norm
pi_loss_norm: true
pi_loss_min_scale: 1
## lazy reanalyze
reanalyze_interval: 10 # 0 means never reanalyze
reanalyze_batch_size: 20 # samples that will be reanalyzed in a batch (should <= batch_size)
reanalyze_horizon: 3
## explore when reanalyze
expl_log_std_min: -2
expl_log_std_max: 1

# training
steps: 1_000_000
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
data_dir: ???

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -3
log_std_max: 1
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 2
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: ???
wandb_entity: ???
wandb_silent: false
disable_wandb: true
save_csv: true

# misc
save_video: true
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???
iter_seq_dim: ???